server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: never
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    database: POSTGRESQL
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      minimum-idle: 2
  sql:
    init:
      platform: postgres
