services:
  db:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
  ollama:
    build: ./docker/ollama/Dockerfile
    volumes:
      - docker/ollama/datafiles:/root/.ollama
    ports:
      - "11434:11434"
